#! /bin/bash

# get script path
export EC_SCRIPT_PATH=$(readlink -f "${BASH_SOURCE[0]}")
export EC_SCRIPT_DIR=$(dirname ${EC_SCRIPT_PATH})
export EC_PATH="ec"

# load dir
function loadDirList() {
    # $1: Dir to load
    # $2: Parameter to receive the result
    unset $2
    i="0"
    for file in $1/*; do
        name="${file#$1/}"

        if [ -d "$file" ]; then
            continue
        elif [ "$name" == "__init__.py" ]; then
            continue
        fi
        
        eval $2[$i]="${name%.py}"
        i=$((i + 1))
    done

    # clean up
    unset file
    unset i
}

function ec_auto_complete() {
	local cmd="${1##*/}"
	local word=${COMP_WORDS[COMP_CWORD]}
	local line=${COMP_LINE}
	local list
	
	# find parameters start with -
	local index=$COMP_CWORD
    for w in ${COMP_WORDS[@]}; do
        if [[ ${w} == -* ]]; then
            index=$((index - 1))
        fi
    done
	
	case "$index" in
	1)
		loadDirList "$EC_SCRIPT_DIR/cfg" "LIST"
		;;
	2)
		loadDirList "$EC_SCRIPT_DIR/cmd" "LIST"
		;;
	esac

	list="${LIST[@]}"
	COMPREPLY=( $(compgen -W "$list" -- "$word") )

	unset LIST
	return 0
}

complete -F ec_auto_complete "$EC_PATH"

unset EC_SCRIPT_PATH
# unset EC_SCRIPT_DIR # keep this value
unset EC_PATH


